version: 2.0

# heavily inspired by https://raw.githubusercontent.com/pinax/pinax-wiki/6bd2a99ab6f702e300d708532a6d1d9aa638b9f8/.circleci/config.yml

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: checkout fixtures submodule
        command: git submodule update --init --recursive
    - run:
        name: merge pull request base
        command: |
          if [[ -n "${CIRCLE_PR_NUMBER}" ]]; then
            PR_INFO_URL=https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls/$CIRCLE_PR_NUMBER

            PR_BASE_BRANCH=$(curl -L "$PR_INFO_URL" | python -c 'import json, sys; obj = json.load(sys.stdin); sys.stdout.write(obj["base"]["ref"])')
            git fetch origin +"$PR_BASE_BRANCH":circleci/pr-base

            # We need these config values or git complains when creating the
            # merge commit
            git config --global user.name "Circle CI"
            git config --global user.email "circleci@example.com"

            git merge --no-edit circleci/pr-base
          fi
    - restore_cache:
        keys:
          - cache-v1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: run tox
        command: ~/.local/bin/tox -r
    - save_cache:
        paths:
          - .hypothesis
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: cache-v1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

jobs:
  lint:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: lint
  py36:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36
  py37:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37
  py38:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: py38
  py39:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV: py39
  py310:
    <<: *common
    docker:
      - image: circleci/python:3.10
        environment:
          TOXENV: py310

workflows:
  version: 2
  test:
    jobs:
      - lint
      - py36
      - py37
      - py38
      - py39
      - py310
